sonar.projectKey=masterteo109_8.2CDevSecOps
sonar.organization=masterteo109
sonar.host.url=https://sonarcloud.io
sonar.login=e902f320f4adbe527b783682dde543152ad584bc

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8